Validation and html

diff --git a/gridStartup/startupchk/startupchk b/gridStartup/startupchk/startupchk
--- a/gridStartup/startupchk/startupchk
+++ b/gridStartup/startupchk/startupchk
@@ -1,16 +1,8 @@
 #!/bin/env bash
 
-GREEN="\033[1;32;40m"
-#ORANGE="\033[33;40m"
-ORANGE="\033[33;44m"
-#RED="\033[1;31;40m"
-RED="\033[1;37;41m"
-#BLUE="\033[1;34;40m"
-BLUE="\033[1;30;46m"
 CYAN="\033[1;36;40m"
 NORM="\033[0m"
 BOLD="\033[1m"
-#BLINK="\033[5m"
 GREEN="\033[1;32;40m"
 ORANGE="\033[33;40m"
 RED="\033[1;31;40m"
@@ -54,6 +46,132 @@ function check_wrkdir ()
 }
 
 
+
+
+validates_clusterware(){
+
+perl_exe=$(which perl|sed 's/\r//')
+
+$perl_exe  $SOURCE/validate.pl "$SOURCE" "$OUTPUTDIR" "$INPUTDIR"
+
+if  [ ! -e $INPUTDIR/raccheck_env.out ]
+ then 
+ echo "Clusterware Node Validation Failed Please Engage Oracle Support to get Assiatnce"
+ else 
+ echo "Clusterware Node Validation Passed !!! ";
+fi
+
+echo "<H2>Cluster Node Validation Summary</H2>"   >> $HTMLFILES/head.part.html
+echo "<table border=1 summary="Cluster Summary" role="presentation">" >> $HTMLFILES/head.part.html
+
+
+echo "<tr><td class="td_column">Collection Date</td><td>$timestamphtml</td></tr>" >> $HTMLFILES/head.part.html
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_HOME"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_HOME"| cut -d\| -f1)
+if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column>CRS Home</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>" >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>CRS Home </td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"    >> $HTMLFILES/head.part.html
+fi
+
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_VERSION"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_VERSION"| cut -d\| -f1)
+if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column>CRS Version</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>"    >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>CRS Version </td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"   >> $HTMLFILES/head.part.html
+fi
+
+
+
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_CRSCONFIGPARAMS"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_CRSCONFIGPARAMS"| cut -d\| -f1)
+if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column>CRS crsconfigparams</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>"  >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>CRS Crsconfigparams </td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"  >> $HTMLFILES/head.part.html
+fi
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_BASE"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLE_BASE"| cut -d\| -f1)
+if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column>CRS Base</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>"  >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>CRS crsconfigparams</td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"  >> $HTMLFILES/head.part.html
+fi
+
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLEOWNER"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "ORACLEOWNER"| cut -d\| -f1)
+if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column>CRS Software Owner</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>"  >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>CRS Software Owner</td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"  >> $HTMLFILES/head.part.html
+fi
+
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "DBAGROUP"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "DBAGROUP"| cut -d\| -f1)
+if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column>CRS Software owner's group</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>"  >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>CRS Software owner's group</td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"  >> $HTMLFILES/head.part.html
+fi
+
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "DBAGROUP"| cut -d\| -f3)
+is_valid=$(cat $INPUTDIR/raccheck_env.out | grep "DBAGROUP"| cut -d\| -f1)
+if [ $is_valid ==  "V" ] ; then echo "<tr><td class=td_column>ASM Disk owner's group</td><td>$VALUE</td><td style="background-color:green">valid</td></tr>"  >> $HTMLFILES/head.part.html
+else echo "<tr><td class=td_column>ASM Disk owner's group</td><td>$VALUE</td><td style="background-color:#00FFFF">invalid</td></tr>"  >> $HTMLFILES/head.part.html
+fi
+
+unset VALUE
+
+VALUE=$(cat $INPUTDIR/raccheck_env.out | grep "HOSTNAME"| wc -l)
+echo "<tr><td class="td_column">Number of nodes</td><td>$VALUE</td></tr>"  >> $HTMLFILES/head.part.html
+
+
+
+cat  "$INPUTDIR/raccheck_env.out" | while read line
+do
+#echo $line
+is_valid=$(echo  $line | grep "HOSTNAME"| cut -d\| -f1)
+is_local=$(echo $line | grep "HOSTNAME"| cut -d\| -f4)
+is_local=$( echo $is_local |sed -r 's/\<./\U&/g')
+is_reached=$(echo $line | grep "HOSTNAME"| cut -d\| -f2)
+node_name=$(echo $line | grep "HOSTNAME"| cut -d\| -f5)
+
+if [[ ! -z $is_valid ]] ; then
+#echo $is_valid
+#echo $is_local
+#echo $is_reached
+#echo $node_name
+     if [ $is_valid == "V" ] ; then echo "<tr><td class=td_column >&nbsp;&nbsp;&nbsp;$is_local</td><td>$node_name</td><td style="background-color:green">$is_reached</td></tr>"  >> $HTMLFILES/head.part.html
+         else echo "<tr><td class=td_column>&nbsp;&nbsp;&nbsp;$is_local</td><td>$node_name</td><td style="background-color:#00FFFF">$is_reached</td></tr>"  >> $HTMLFILES/head.part.html
+fi
+fi
+done
+
+
+echo "</table>" >>$HTMLFILES/head.part.html
+
+ 
+}
+
+initialize_htmlhead(){
+
+
+cp  $SOURCE/html/head.part.html  $HTMLFILES/head.part.html
+
+echo "<title>Oracle CLusterware Startup Assessment Report</title>"   >> $HTMLFILES/head.part.html
+echo "<meta name="FILE Name" content=FILE_NAME = CLUSTERWARE STARTUP ASSESSMENT REPORT>"   >> $HTMLFILES/head.part.html
+echo "<meta name="FILE DATE" content=FILE_DATE = {timestamphtml}>" >> $HTMLFILES/head.part.html
+echo "</head><body>" >> $HTMLFILES/head.part.html
+
+echo "<center><table border=0 width=100%><tr><td class="td_title" align="center">"   >> $HTMLFILES/head.part.html  
+echo " <h1>Oracle CLusterware Startup Assessment Report<br><br>"  >> $HTMLFILES/head.part.html
+echo "</td></tr></table></center>"    >> $HTMLFILES/head.part.html
+
+
+}
+
 initialize ()
 {
 
@@ -67,6 +185,15 @@ initialize ()
   if [ $bash_found -ne 0 ]
   then
     echo -e "\n${RED}${program_name} requires the BASH shell. Please install bash and try again.${NORM}\n"
+    exit 1;
+  fi
+ 
+ 
+  perl_found=$(which perl >/dev/null 2>&1;echo $?)
+
+  if [ $perl_found -ne 0 ]
+  then
+    echo -e "\n${RED}${program_name} requires the Perl to be installed . Please install perl or set the PATH vaarible and try again.${NORM}\n"
     exit 1;
   fi
 
@@ -110,7 +237,7 @@ initialize ()
   check_wrkdir
 
   PROFILE=$SCRIPTPATH/src/profile.dat
-  SOURCE==$SCRIPTPATH/src
+  SOURCE=$SCRIPTPATH/src
 
   INPUTDIR=${WRKDIR}/.input_${timestamp}
   mkdir $INPUTDIR
@@ -125,14 +252,22 @@ initialize ()
   MASTERFIL=$INPUTDIR/raccheck_env.out
   RTEMPDIR=$INPUTDIR
 
+  HTMLFILES=$OUTPUTDIR/html/
+  mkdir $HTMLFILES
+  
+  LOGFILE=$OUTPUTDIR/log
+  mkdir $LOGFILE
+  
+  
   SREPFIL=$OUTPUTDIR/html/${program_name}_summary.rep
   WATCHLOG=$OUTPUTDIR/log/watchdog.log
  
-
-
+  initialize_htmlhead
+ 
+ 
 }
 
-
+timestamphtml=$(date '+%Y-%m-%d %H:%M:%S')
 timestamp=$(date '+%Y%m%d_%H%M%S')
 program_name=$(echo $(basename $0)|sed 's/[\.\/]//g')
 
@@ -339,6 +474,9 @@ $WATCHDOG &
 
 watchdog_pid=$!
 
+validates_clusterware
+
+
 
 #/temp/sample.sh
 #cho "sample 1 is running"
@@ -350,13 +488,8 @@ watchdog_pid=$!
 #cho "sample 3 is running"
 
 
-#ill -9 $watchdog_pid
+kill -9 $watchdog_pid
 #end_long_comment
-
-
-
-
- ./newvalidate.pl $HOSTLIST $MASTERFIL
 
 
 
